# Alacritty Configuration

[window]
opacity = 1
startup_mode = "Windowed"
dynamic_title = true
decorations_theme_variant = "Dark"
blur = false
padding = { x = 0, y = 0 }

[font]
normal = { family = "JetBrainsMono Nerd Font" }
size = 14.0

[cursor]
style = "Block"

[shell]
program = "/bin/zsh"
args = ["--login"]

# Default colors
[colors.primary]
background = "0x282828"
foreground = "0xebdbb2"

# Normal colors
[colors.normal]
black = "0x282828"
red = "0xcc241d"
green = "0x98971a"
yellow = "0xd79921"
blue = "0x458588"
magenta = "0xb16286"
cyan = "0x689d6a"
white = "0xa89984"

# Bright colors
[colors.bright]
black = "0x928374"
red = "0xfb4934"
green = "0xb8bb26"
yellow = "0xfabd2f"
blue = "0x83a598"
magenta = "0xd3869b"
cyan = "0x8ec07c"
white = "0xebdbb2"

# Dim colors
[colors.dim]
black = "0x32302f"
red = "0x9d0006"
green = "0x79740e"
yellow = "0xb57614"
blue = "0x076678"
magenta = "0x8f3f71"
cyan = "0x427b58"
white = "0x928374"

[colors.selection]
text = "CellForeground"
background = "0xb57614"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "N"
mods = "Command"
action = "SpawnNewInstance"

[[keyboard.bindings]]
key = "Return"
mods = "Command"
action = "ToggleFullScreen"

[scrolling]
history = 10000
multiplier = 3
