# Alacritty Configuration

[window]
opacity = 1
decorations = "Transparent"
startup_mode = "Windowed"
dynamic_title = true
decorations_theme_variant = "Dark"
blur = false
padding = { x = 0, y = 25 }

[font]
normal = { family = "JetBrainsMono Nerd Font" }
size = 14.0

[cursor]
style = "Block"

[shell]
program = "/bin/zsh"
args = ["--login"]

[colors]

[colors.primary]
background = "0x1E1E2E"
foreground = "0xCDD6F4"

[colors.normal]
black = "0x45475A"
red = "0xF38BA8"
green = "0xA6E3A1"
yellow = "0xF9E2AF"
blue = "0x89B4FA"
magenta = "0xF5C2E7"
cyan = "0x94E2D5"
white = "0xBAC2DE"

[colors.bright]
black = "0x585B70"
red = "0xF38BA8"
green = "0xA6E3A1"
yellow = "0xF9E2AF"
blue = "0x89B4FA"
magenta = "0xF5C2E7"
cyan = "0x94E2D5"
white = "0xA6ADC8"


[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "N"
mods = "Command"
action = "SpawnNewInstance"

[[keyboard.bindings]]
key = "Return"
mods = "Command"
action = "ToggleFullScreen"

[scrolling]
history = 10000
multiplier = 3
