# Alacritty Configuration

[window]
opacity = 0.9
decorations = "full"
startup_mode = "Windowed"
dynamic_title = true
decorations_theme_variant = "Dark"
blur = true

[font]
normal = { family = "JetBrainsMono Nerd Font" }
size = 13.0

[cursor]
style = "Block"

[shell]
program = "/bin/zsh"
args = ["--login"]

[colors]
[colors.primary]
background = "0x1E1E2E"
foreground = "0xD9E0EE"

[colors.normal]
black = "0x1E1E2E"
red = "0xF28FAD"
green = "0xABE9B3"
yellow = "0xFAE3B0"
blue = "0x96CDFB"
magenta = "0xF5C2E7"
cyan = "0x89DCEB"
white = "0xD9E0EE"

[colors.bright]
black = "0x6E6C7E"
red = "0xF28FAD"
green = "0xABE9B3"
yellow = "0xFAE3B0"
blue = "0x96CDFB"
magenta = "0xF5C2E7"
cyan = "0x89DCEB"
white = "0xD9E0EE"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "N"
mods = "Command"
action = "SpawnNewInstance"

[[keyboard.bindings]]
key = "Return"
mods = "Command"
action = "ToggleFullScreen"

[scrolling]
history = 10000
multiplier = 3
