# ~/.config/starship.toml
add_newline = false                           # keep it all on one line
format = """
$character\
$directory\
$git_branch\
$git_status """

[directory]                                   #  ~/code/ecomm-backend
style = "blue"
truncate_to_repo   = false
truncation_length  = 3
truncation_symbol  = "../"

[git_branch]                                  #  git:(my-branch)
format = "[git](red bold):[$branch](green bold)"

[git_status]                                  #  ✚ ✱ etc. (appears only when dirty)
format = ' [$staged$modified$untracked$conflicted$deleted$ahead_behind]($style)'
style  = "bold red"                           # red = “pending changes”
staged     = "●"
modified   = "✱"
untracked  = "✚"
conflicted = "⚔️"
deleted    = "✘"
ahead      = "⇡$count"
behind     = "⇣$count"
diverged   = "⇕"

[character]                                   # prompt symbol
success_symbol = "[➜](cyan)"                  # clean repo → no red segment, cyan arrow
